export const CartActionTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
  DESCREASE_QUANTITY: "DESCREASE_QUANTITY",
  CLEAR_CART: "CLEAR_CART"
};
